const messages = {
    EMAIL_ALREADY_REGISTERED: "Email already registered",
    SIGNUP_FAILED: "Invitation failed. Please try again.",
    LOGIN_SUCCESSFULL: "Login successful!",
    PENDING_USER: "Your account is pending approval. Please wait for verification.",
    BLOCKED_USER: "Your account has been blocked.",
    INTERNAL_SERVER_ERROR: "Internal server error.",
    SIGNUP_SUCCESSFULL: `Signup successful! Please check your email`,
    USER_NOT_FOUND: "User not found",
    ACCESS_DENIED: "Access Denied",
    INVALID_TOKEN: "Invalid Token",
    VERIFY_EMAIL_FIRST: "Please verify your email first.",
    INVALID_CREDENTIALS: "Invalid credentials",
    PROFILE_UPDATED: "Profile updated successfully!",
    NO_PROFILE_CHANGES: "No changes made to the profile.",
    PASSWORD_REQUIRED: "Both old and new passwords are required",
    INCORRECT_OLD_PASSWORD: "Incorrect old password",
    PASSWORD_CHANGED: "Password changed successfully",
    PASSWORD_CHANGE_FAILED: "Unable to change password",
    RECOVERY_EMAIL_SENT: "A recovery email has been sent to your email address to reset your password",
    PASSWORD_UPDATED: "Password updated successfully!",
    USER_CREATED: "User created successfully.",
    USER_DELETED: "User deleted successfully.",
    DATA_RETRIEVED: "Data retrieved successfully.",
    SOMETHING_WENT_WRONG: "Something went wrong!.",
    DASHBOARD_DATA_RETRIEVED: "Dashboard data retrieved successfully.",
    STATUS_CHANGED: "Status changed successfully",
    PERMISSION_UPDATED: "Permissions updated successfully.",
    PERMISSION_NOT_FOUND: "Permissions not found.",
    CASE_TYPE_NOT_FOUND: "Case type not found.",
    CASE_NOT_FOUND: "Case not found.",
    CASE_CREATED: "Case created successfully.",
    CASE_CREATION_FAILED: "Case creation failed.",
    CASE_UPDATED: "Case updated successfully.",
    CASE_UPDATE_FAILED: "Case update failed.",
    PEOPLE_ADDED: "People added successfully.",
    PEOPLE_ADDED_FAILED: "People addition failed.",
    CASE_PEOPLE_NOT_FOUND: "People not found.",
    PEOPLE_DELETED: "People deleted successfully",
    CASE_DELETED: "Case deleted successfully",
    PROPERTY_ADDED: "Property added successfully.",
    PROPERTY_ADDED_FAILED: "Property addition failed.",
    CASE_PROPERTY_NOT_FOUND: "Property not found.",
    CREDIT_ADDED: "Credit added successfully.",
    CREDIT_ADDED_FAILED: "Credit addition failed.",
    CASE_CREDIT_NOT_FOUND: "Credit not found.",
    LOAN_ADDED: "Laon added successfully.",
    LOAN_ADDED_FAILED: "Laon addition failed.",
    CASE_LOAN_NOT_FOUND: "Laon not found.",
    INVESTMENT_ADDED: "Investment added successfully.",
    INVESTMENT_ADDED_FAILED: "Investment addition failed.",
    CASE_INVESTMENT_NOT_FOUND: "Investment not found.",
    EXPENSE_ADDED: "Expense added successfully.",
    EXPENSE_ADDED_FAILED: "Expense addition failed.",
    CASE_EXPENSE_NOT_FOUND: "Expense not found.",
    TOTAL_ADDED: "Total added successfully.",
    TOTAL_ADDED_FAILED: "Total addition failed.",
    CASE_TOTAL_NOT_FOUND: "Total not found.",
    REDUCTION_ADDED: "Reduction added successfully.",
    REDUCTION_ADDED_FAILED: "Reduction addition failed.",
    CASE_REDUCTION_NOT_FOUND: "Reduction not found.",
    POLICY_ADDED: "Policy added successfully.",
    POLICY_ADDED_FAILED: "Policy addition failed.",
    CASE_POLICY_NOT_FOUND: "Policy not found.",
    FINAL_TOTAL_ADDED: "Final total added successfully.",
    FINAL_TOTAL_ADDED_FAILED: "Final total addition failed.",
    CASE_FINAL_TOTAL_NOT_FOUND: "Final total not found.",
    NO_CLIENTS_FOUND_FOR_AGENT: "No clients found for this agent.",
    COMBINED_POILCY_DATA_NOT_FOUND: "Combined policy data not found.",
    POILCY_DATA_NOT_FOUND: "Policy data not found.",
    REPORT_DATA_NOT_FOUND: "Final report data not found.",
    COMBINED_POILCY_DATA_INSERTED: "Policy data inserted successfully.",
    COMBINED_POILCY_DATA_INSERTED_FAILED: "Failed to upload policy data",
};

export default messages