const messages = {
    EMAIL_ALREADY_REGISTERED: "This email is already registered.",
    SIGNUP_FAILED: "Signup failed. Please try again.",
    LOGIN_SUCCESSFUL: "Login successful!",
    PENDING_USER: "Your account is pending approval. Please wait for verification.",
    BLOCKED_USER: "Your account has been blocked.",
    INTERNAL_SERVER_ERROR: "Internal server error occurred.",
    SIGNUP_SUCCESSFUL: "Signup successful! Please check your email for verification.",
    USER_NOT_FOUND: "User not found.",
    ACCESS_DENIED: "Access denied.",
    INVALID_TOKEN: "Invalid token provided.",
    VERIFY_EMAIL_FIRST: "Please verify your email before proceeding.",
    INVALID_CREDENTIALS: "Invalid login credentials.",
    PROFILE_UPDATED: "Profile updated successfully.",
    NO_PROFILE_CHANGES: "No changes were made to the profile.",
    PASSWORD_REQUIRED: "Both old and new passwords are required.",
    INCORRECT_OLD_PASSWORD: "Incorrect old password.",
    PASSWORD_CHANGED: "Password changed successfully.",
    PASSWORD_CHANGE_FAILED: "Failed to change password.",
    RECOVERY_EMAIL_SENT: "A password recovery email has been sent to your address.",
    PASSWORD_UPDATED: "Password updated successfully.",
    USER_CREATED: "User created successfully.",
    USER_DELETED: "User deleted successfully.",
    DATA_RETRIEVED: "Data retrieved successfully.",
    SOMETHING_WENT_WRONG: "Something went wrong. Please try again.",
    DASHBOARD_DATA_RETRIEVED: "Dashboard data retrieved successfully.",
    STATUS_CHANGED: "Status updated successfully.",
    PERMISSION_UPDATED: "Permissions updated successfully.",
    PERMISSION_NOT_FOUND: "Permissions not found.",
    CASE_TYPE_NOT_FOUND: "Case type not found.",
    CASE_NOT_FOUND: "Case not found.",
    CASE_CREATED: "Case created successfully.",
    CASE_CREATION_FAILED: "Failed to create case.",
    CASE_UPDATED: "Case updated successfully.",
    CASE_UPDATE_FAILED: "Failed to update case.",
    PEOPLE_ADDED: "People added successfully.",
    PEOPLE_ADDITION_FAILED: "Failed to add people.",
    CASE_PEOPLE_NOT_FOUND: "People not found for the case.",
    PEOPLE_DELETED: "People deleted successfully.",
    CASE_DELETED: "Case deleted successfully.",
    PROPERTY_ADDED: "Property added successfully.",
    PROPERTY_ADDITION_FAILED: "Failed to add property.",
    CASE_PROPERTY_NOT_FOUND: "Property not found for the case.",
    CREDIT_ADDED: "Credit added successfully.",
    CREDIT_ADDITION_FAILED: "Failed to add credit.",
    CASE_CREDIT_NOT_FOUND: "Credit not found for the case.",
    LOAN_ADDED: "Loan added successfully.",
    LOAN_ADDITION_FAILED: "Failed to add loan.",
    CASE_LOAN_NOT_FOUND: "Loan not found for the case.",
    INVESTMENT_ADDED: "Investment added successfully.",
    INVESTMENT_ADDITION_FAILED: "Failed to add investment.",
    CASE_INVESTMENT_NOT_FOUND: "Investment not found for the case.",
    EXPENSE_ADDED: "Expense added successfully.",
    EXPENSE_ADDITION_FAILED: "Failed to add expense.",
    CASE_EXPENSE_NOT_FOUND: "Expense not found for the case.",
    TOTAL_ADDED: "Total added successfully.",
    TOTAL_ADDITION_FAILED: "Failed to add total.",
    CASE_TOTAL_NOT_FOUND: "Total not found for the case.",
    REDUCTION_ADDED: "Reduction added successfully.",
    REDUCTION_ADDITION_FAILED: "Failed to add reduction.",
    CASE_REDUCTION_NOT_FOUND: "Reduction not found for the case.",
    POLICY_ADDED: "Policy added successfully.",
    POLICY_ADDITION_FAILED: "Failed to add policy.",
    CASE_POLICY_NOT_FOUND: "Policy not found for the case.",
    FINAL_TOTAL_ADDED: "Final total added successfully.",
    FINAL_TOTAL_ADDITION_FAILED: "Failed to add final total.",
    CASE_FINAL_TOTAL_NOT_FOUND: "Final total not found for the case.",
    NO_CLIENTS_FOUND_FOR_AGENT: "No clients found for this agent.",

    COMBINED_POLICY_DATA_NOT_FOUND: "Combined policy data not found.",
    POLICY_DATA_NOT_FOUND: "Policy data not found.",
    REPORT_DATA_NOT_FOUND: "Final report data not found.",
    COMBINED_POLICY_DATA_INSERTED: "Policy data uploaded successfully.",
    COMBINED_POLICY_DATA_INSERTION_FAILED: "Failed to upload policy data.",
    CASE_SYNCED: "Case copy synced successfully.",
    CASE_COPIED: "Case copy created successfully.",
    CLIENT_PLAN_CREATED: "Client plan created successfully.",
};

export default messages