export const POLICY_LOAN_FACTOR_YEAR_ONE = 0.828;
export const POLICY_LOAN_FACTOR_OTHER_YEARS = 0.9;
export const POLICY_LOAN_INTEREST_RATE = 6.2;
export const HELOC_EQUITY_FACTOR = 0.65;
export const CREDIT_MINIMUM_PAYMENT_FACTOR = 0.03;
export const ANNUAL_INCOME_GROWTH_RATE = 1.03;
export const ANNUAL_INVESTMENTS_GROWTH_RATE = 1.04;
export const RECOMMENDED_INSURANCE_AMOUNT_INCOME_CALCULATION_FACTOR = 0.035;
